version: '3'

services:
  postgres:
    image: postgres
    container_name: "basejump-postgres"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: "basejump-keycloak"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    command:
      - start-dev
